Repository kubernetes-sigs/aws-encryption-provider, pull requests merged in 2019-05, with the labels that each got.

#11 Updated Go version, AWS SDK, and added go modules
  .gitignore
  Dockerfile
  Makefile
  cmd/client/main.go
  cmd/server/main.go
  go.mod
  go.sum
  pkg/cloud/cloud.go
  pkg/cloud/mock.go
  pkg/connection/connection.go
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
  pkg/server/server.go
  pkg/version/version.go
  test/integration/integration_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#10 Added lint target
  Makefile
  cmd/server/main.go
  hack/verify-golint.sh
  test/integration/integration_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#14 Added micahhausler as maintainer
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#12 fix flaky tests
  Gopkg.lock
  Gopkg.toml
  cmd/server/main.go
  go.mod
  go.sum
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
  test/integration/integration_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#15 Added godoc comments
  pkg/connection/connection.go
  pkg/plugin/plugin.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#16 Updated security contacts, added micahhausler to administrator
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  OWNERS_ALIASES
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/M
