Repository kubernetes-sigs/aws-encryption-provider, pull requests merged in 2019-08, with the labels that each got.

#30 Add additional docs for kops bootstrap
  KOPS.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#35 Updated aws-sdk-go to v1.23.11
  Makefile
  go.mod
  go.sum
  hack/verify-golint.sh
  hack/verify-vendor.sh
  vendor/github.com/aws/aws-sdk-go/aws/awserr/types.go
  vendor/github.com/aws/aws-sdk-go/aws/awsutil/path_value.go
  vendor/github.com/aws/aws-sdk-go/aws/client/default_retryer.go
  vendor/github.com/aws/aws-sdk-go/aws/client/logger.go
  vendor/github.com/aws/aws-sdk-go/aws/config.go
  vendor/github.com/aws/aws-sdk-go/aws/corehandlers/handlers.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/credentials.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/endpointcreds/provider.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/stscreds/assume_role_provider.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/stscreds/web_identity_provider.go
  vendor/github.com/aws/aws-sdk-go/aws/csm/doc.go
  vendor/github.com/aws/aws-sdk-go/aws/csm/enable.go
  vendor/github.com/aws/aws-sdk-go/aws/csm/reporter.go
  vendor/github.com/aws/aws-sdk-go/aws/ec2metadata/service.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/endpoints.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/v3model.go
  vendor/github.com/aws/aws-sdk-go/aws/request/connection_reset_error.go
  vendor/github.com/aws/aws-sdk-go/aws/request/connection_reset_error_other.go
  vendor/github.com/aws/aws-sdk-go/aws/request/handlers.go
  vendor/github.com/aws/aws-sdk-go/aws/request/offset_reader.go
  vendor/github.com/aws/aws-sdk-go/aws/request/request.go
  vendor/github.com/aws/aws-sdk-go/aws/request/request_1_8.go
  vendor/github.com/aws/aws-sdk-go/aws/request/request_pagination.go
  vendor/github.com/aws/aws-sdk-go/aws/request/retryer.go
  vendor/github.com/aws/aws-sdk-go/aws/session/credentials.go
  vendor/github.com/aws/aws-sdk-go/aws/session/doc.go
  vendor/github.com/aws/aws-sdk-go/aws/session/env_config.go
  vendor/github.com/aws/aws-sdk-go/aws/session/session.go
  vendor/github.com/aws/aws-sdk-go/aws/session/shared_config.go
  vendor/github.com/aws/aws-sdk-go/aws/signer/v4/v4.go
  vendor/github.com/aws/aws-sdk-go/aws/types.go
  vendor/github.com/aws/aws-sdk-go/aws/version.go
  vendor/github.com/aws/aws-sdk-go/internal/ini/ini_parser.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/rest/unmarshal.go
  vendor/github.com/aws/aws-sdk-go/service/kms/api.go
  vendor/github.com/aws/aws-sdk-go/service/kms/errors.go
  vendor/github.com/aws/aws-sdk-go/service/sts/api.go
  vendor/github.com/aws/aws-sdk-go/service/sts/customizations.go
  vendor/github.com/aws/aws-sdk-go/service/sts/doc.go
  vendor/github.com/aws/aws-sdk-go/service/sts/stsiface/interface.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#37 Fixed build badge
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
