Repository kubernetes-sigs/aws-encryption-provider, pull requests merged in 2020-01, with the labels that each got.

#49 use vendor directory to build
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#50 update copyright year to 2020
  cmd/client/main.go
  cmd/server/main.go
  pkg/cloud/cloud.go
  pkg/cloud/mock.go
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
  pkg/server/server.go
  pkg/version/version.go
  test/integration/integration_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#48 update go version
  .travis.yml
  Dockerfile
  go.mod
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#51 allow user to override aws endpoint
  cmd/server/main.go
  pkg/cloud/cloud.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#53 remove installsuffix cgo and add -w -s ldflags
  Dockerfile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#52 make use of vendor directory consistent
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#55 Added Gyuho Lee as owner
  OWNERS_ALIASES
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#44 Dockerfile: build from "busybox" to include "/bin/sh"
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#57 remove cat statement that was added for debugging test failure
  hack/verify-vendor.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#58 allow debug logging and add logging to encrypt/decrypt operations
  cmd/server/main.go
  pkg/logging/zap.go
  pkg/plugin/plugin.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#59 *: support KMS API call rate-limiting
  cmd/server/main.go
  go.mod
  go.sum
  pkg/cloud/cloud.go
  pkg/httputil/client.go
  pkg/httputil/client_test.go
  vendor/golang.org/x/time/AUTHORS
  vendor/golang.org/x/time/CONTRIBUTORS
  vendor/golang.org/x/time/LICENSE
  vendor/golang.org/x/time/PATENTS
  vendor/golang.org/x/time/rate/rate.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#60 *: support encryption context
  cmd/server/main.go
  go.mod
  go.sum
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
  test/integration/integration_test.go
  vendor/github.com/spf13/pflag/.gitignore
  vendor/github.com/spf13/pflag/.travis.yml
  vendor/github.com/spf13/pflag/LICENSE
  vendor/github.com/spf13/pflag/README.md
  vendor/github.com/spf13/pflag/bool.go
  vendor/github.com/spf13/pflag/bool_slice.go
  vendor/github.com/spf13/pflag/bytes.go
  vendor/github.com/spf13/pflag/count.go
  vendor/github.com/spf13/pflag/duration.go
  vendor/github.com/spf13/pflag/duration_slice.go
  vendor/github.com/spf13/pflag/flag.go
  vendor/github.com/spf13/pflag/float32.go
  vendor/github.com/spf13/pflag/float32_slice.go
  vendor/github.com/spf13/pflag/float64.go
  vendor/github.com/spf13/pflag/float64_slice.go
  vendor/github.com/spf13/pflag/go.mod
  vendor/github.com/spf13/pflag/go.sum
  vendor/github.com/spf13/pflag/golangflag.go
  vendor/github.com/spf13/pflag/int.go
  vendor/github.com/spf13/pflag/int16.go
  vendor/github.com/spf13/pflag/int32.go
  vendor/github.com/spf13/pflag/int32_slice.go
  vendor/github.com/spf13/pflag/int64.go
  vendor/github.com/spf13/pflag/int64_slice.go
  vendor/github.com/spf13/pflag/int8.go
  vendor/github.com/spf13/pflag/int_slice.go
  vendor/github.com/spf13/pflag/ip.go
  vendor/github.com/spf13/pflag/ip_slice.go
  vendor/github.com/spf13/pflag/ipmask.go
  vendor/github.com/spf13/pflag/ipnet.go
  vendor/github.com/spf13/pflag/string.go
  vendor/github.com/spf13/pflag/string_array.go
  vendor/github.com/spf13/pflag/string_slice.go
  vendor/github.com/spf13/pflag/string_to_int.go
  vendor/github.com/spf13/pflag/string_to_int64.go
  vendor/github.com/spf13/pflag/string_to_string.go
  vendor/github.com/spf13/pflag/uint.go
  vendor/github.com/spf13/pflag/uint16.go
  vendor/github.com/spf13/pflag/uint32.go
  vendor/github.com/spf13/pflag/uint64.go
  vendor/github.com/spf13/pflag/uint8.go
  vendor/github.com/spf13/pflag/uint_slice.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#62 pkg/httputil: mask "dial i/o timeout" error in "TestNewRateLimitedClient"
  pkg/httputil/client_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
