Repository kubernetes-sigs/aws-encryption-provider, pull requests merged in 2022-12, with the labels that each got.

#89 Bump aws-sdk-go version to v1.44.145
  go.mod
  go.sum
  hack/verify-golint.sh
  pkg/plugin/plugin.go
  pkg/server/server.go
  pkg/tools/tools.go
Labels: cncf-cla: yes, size/XL, lgtm, approved, ok-to-test

#90 Update OWNERS_ALIASES
  OWNERS_ALIASES
Labels: cncf-cla: yes, lgtm, size/XS, approved

#88 chore: finish update to go 1.19
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  Dockerfile
Labels: cncf-cla: yes, lgtm, size/S, approved, ok-to-test
