Repository kubernetes-sigs/aws-encryption-provider, pull requests merged in 2024-01, with the labels that each got.

#101 Switch to use go-version file from go-image-tag
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  .go-image-tag
  .go-version
  hack/setup-go.sh
Labels: cncf-cla: yes, lgtm, size/S, approved

#102 CVE patch
  .go-version
  Dockerfile
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, size/M, approved

#103 release encryption provider exclude KMS v2
  Makefile
  cmd/clientv2/main.go
  cmd/server/main.go
  go.mod
  go.sum
  pkg/healthz/healthz.go
  pkg/healthz/healthz_test.go
  pkg/kmsplugin/kms.go
  pkg/livez/livez.go
  pkg/livez/livez_test.go
  pkg/plugin/metrics.go
  pkg/plugin/metrics_test.go
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
  pkg/plugin/plugin_v2.go
  pkg/plugin/plugin_v2_test.go
  pkg/plugin/shared_health_check.go
  test/integration/integration_test.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved

#104 Update OWNERS_ALIASES
  OWNERS_ALIASES
Labels: cncf-cla: yes, lgtm, size/XS, approved
