Repository kubernetes-sigs/aws-encryption-provider, pull requests merged in 2025-04, with the labels that each got.

#132 Adding yue9944882 to approver list
  OWNERS_ALIASES
Labels: cncf-cla: yes, lgtm, size/XS, approved

#120 Switch to aws-sdk-go-v2
  .gitignore
  .goreleaser.yml
  cmd/server/main.go
  go.mod
  go.sum
  pkg/cloud/cloud.go
  pkg/cloud/cloud_test.go
  pkg/cloud/mock.go
  pkg/healthz/healthz_test.go
  pkg/httputil/client.go
  pkg/httputil/client_test.go
  pkg/kmsplugin/kms.go
  pkg/livez/livez_test.go
  pkg/plugin/metrics_test.go
  pkg/plugin/plugin.go
  pkg/plugin/plugin_test.go
  pkg/plugin/plugin_v2.go
  pkg/plugin/plugin_v2_test.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved

#133 update the go version to 1.24.2
  .go-version
  .travis.yml
  Dockerfile
  cmd/client/main.go
  cmd/clientv2/main.go
  go.mod
  hack/verify-golint.sh
  pkg/cloud/cloud_test.go
  pkg/healthz/healthz.go
  pkg/healthz/healthz_test.go
  pkg/kmsplugin/kms.go
  pkg/livez/livez.go
  pkg/livez/livez_test.go
  pkg/plugin/metrics_test.go
  pkg/plugin/plugin_test.go
  pkg/plugin/plugin_v2_test.go
  pkg/server/server.go
  pkg/server/server_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#134 v1.33.0 Release
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test
