Repository kubernetes-sigs/aws-encryption-provider, pull requests merged in 2025-05, with the labels that each got.

#136 Cloudbuild for releasing official container
  cloudbuild.yaml
Labels: cncf-cla: yes, lgtm, size/S, approved, ok-to-test

#137 fix: failing build due to invalid IMAGE override in container builds
  cloudbuild.yaml
Labels: cncf-cla: yes, lgtm, size/XS, needs-ok-to-test, approved

#138 Add metric category for failures due to corruption and remove from he…
  pkg/kmsplugin/kms.go
  pkg/plugin/plugin.go
  pkg/plugin/plugin_v2.go
  pkg/plugin/plugin_v2_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test
